Criar der bd
jhenriquelc/VelocityVanguards-2024.2 pull request #33
Opened 2024-12-13 13:11 UTC by MarceloAngeli

Adicionado o DER do banco de dados assim como o código de criação do mesmo.

2024-12-13 18:35 UTC, jhenriquelc commented
Como q foi parar um commit velho meu aí? 💀

Sempre crie branches a partir da main quando aplicável:
```
git switch main
git pull
git switch -c <branch-nova>
```

Vou resolver isso manualmente (rolo com `git rebase -i` seguido de force push), pfvr não commita nada na branch, depois entra na sua cópia da branch e usa `git pull` e então, ignorando o erro, um `git reset --hard origin/<nome_da_branch>`.

Isso vai apagar qualquer coisa na branch antes do reset, então tenha cuidado.

Postarei aqui a sequência de comandos que usarei para resolver o conflito. Por favor leia e analise para entender como resolver coisas assim no futuro.

2024-12-13 18:38 UTC, jhenriquelc requested changes, later dismissed

2024-12-13 18:38 UTC, jhenriquelc commented on Site/package.json
DER não precisa mexer nas dependências do site?!

2024-12-13 18:57 UTC, jhenriquelc commented
Vou aproveitar que vou dar rebase nisso e mudar as mensagens de commit que estão fora do padrão.

2024-12-13 19:18 UTC, s4un3 requested changes

2024-12-13 19:18 UTC, s4un3 commented on DocumentacaoBD/DER.png
Talvez seja interessante ter uma coluna na tabela de funcionário para "credenciais". Sugiro que essas credenciais sejam compostas de um cpf e um hash da senha (ambos varchar), e o cpf seja a PK.

2024-12-24 14:29 UTC, MarceloAngeli commented on DocumentacaoBD/DER.png
Realmente, ta errado mesmo. Vou adicionar aqui.

2024-12-24 16:32 UTC, MarceloAngeli commented
Cara apanhei que nem criança diz que eu não fiz merda pelo amor de Deus.

2024-12-25 22:03 UTC, jhenriquelc commented
O commit mexeu no gitignore, pq?

2025-01-02 20:42 UTC, jhenriquelc approved these changes

2025-01-02 21:16 UTC, s4un3 approved these changes

2025-01-02 21:16 UTC, merged